### ISSUE TITLE
Custom title screen song for OpenRCT2

### ISSUE THREAD

**Issue by Nubbie** [OpenRCT2/OpenMusic#2]
As we have a custom title screen - Why not a custom song

The song should be a alteration on the RCT2 song
The only one I had in mind would be https://youtu.be/tvD2cXa4KJM which is a remix off the RCT2 song
Suggested on OpenRCT2/OpenRCT2#5034

**Comment by ccoors** [comment]
As said in the other issue, this won't be possible, because the RCT2 song is an original song by Allister Brimble. We'll need another one.

**Comment by grimpunch** [comment]
Crazy out of the blue suggestion I know, but I was curious whether Frühlingssänger op.426 is public domain now or not, and if so, whether you think a rendition of that would make for a good theme?

**Comment by ccoors** [comment]
So far the list of possible songs consists of

- Sinfonia from Cantata No. 29 by Bach
- Sortie in Eb by Lefébure-Wély
- Frühlingssänger (op. 426) by Lange

Frühlingssänger sounds pretty nice, but I couldn't find any sheet music yet. Lange died in 1889, so it is public domain in most countries, I wouldn't worry about that.

**Comment by ccoors** [comment]
Note to self:

Hans Christian Lumbye
- Britta Polka
- Steam Railway Galop
- other Waltzes/Galops

**Comment by ccoors** [comment]
Other option:
- BWV 563 - Fantasia

**Comment by ExileFox** [comment]
Ccmixter has a lot of content, I think digging through it could yield some great results.

**Comment by ccoors** [comment]
New Idea: Prestissimo Galop by Émile Waldteufel

Maybe too fast. But would work as an alternative music for the fairground style.

**Comment by ExileFox** [comment]
A few suggestions to have a look at:

Title screen:
http://dig.ccmixter.org/files/airtone/57869

Ride music:
http://dig.ccmixter.org/files/airtone/58011
http://dig.ccmixter.org/files/onlymeith/57861

**Comment by ccoors** [comment]
@spacek531 You currently make the title sequences for OpenRCT2 and afaik you sync them with the title music. Are there any requirements from your side for the new title music? I would definitely go for a Waltz again, but should it for example be in the same tempo as the original RCT2 title music so the title sequence syncs with both?

**Comment by spacek531** [comment]
The best quality I can think of for a title sequence song is a musical *something* like an instrument change or a change from chorus to verse, or whatever, at a consistent interval. The three variations of RCT1 title sequences had shots that lasted multiples of 5 seconds -- 5, 10, 15, 20. Music that I can edit the sequence to with interval multiples like in RCT1 is, in my opinion, going to be the easiest to work with.

This opinion could change, but that is my best estimate at this time.

**Comment by ExileFox** [comment]
@ccoors @spacek531 please take a look at my suggestions

**Comment by ccoors** [comment]
@Patrik356b That doesn't really work as the title music. I want something in the style of RCT1/2. On the ride music I don't really have an opinion, it might work.

**Comment by mattheasboelter** [comment]
Hi, I'm currently working on some original title music. The project files (musescore and lmms) have been merged in. This is what is sounds like:

https://soundcloud.com/tardis-maker/openrct2-main-title-2-lmms/s-6f7yt

If you have feedback plese let me know.

@ccoors Should we close this, or save it until we get to the final iteration? I understand that we will use something dirived from what I've written, so the search for music is over.

**Comment by ccoors** [comment]
Good point. Yes, I don't think we need this issue open any more.
