### ISSUE TITLE
Problematic soundfont licenses

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenMusic#22]
Two of the soundfonts that are used to "build" the music have problematic licenses, which would prevent inclusion of any resulting music files generated with them from being included in third-party packaging, such as you might see in a Linux distribution.

* "GeneralUser GS v1.471" -- I am uncomfortable with the phrase "I cannot be 100% sure where all of the samples originated" within that license and the resulting ambiguity of whether the author actually is actually distributing his own work or not.
* "K18-Upright-Piano" -- While the author may have granted the OpenRCT2 project permission to use/distribute the audio samples, that does not extend to anyone who receives a copy of it. This is clearly non-free.

It would be great if truly free soundfonts could be used instead.

(I'm approaching this with Debian's [DFSG](https://www.debian.org/social_contract#guidelines) in mind, but I know other Linux distributions have similar philosophies on what sort of software they will include.)

**Comment by IntelOrca** [comment]
@gibmat the latest release currently does not contain any of the things you mention. The release only has audio files created by @karst which are appropriately licenced for a Linux distribution.

**Comment by Gymnasiast** [comment]
I don’t think they were *ever* in the repo or build to begin - I don’t know why @ccoors added the licences though - maybe he can help us with that.

**Comment by Gymnasiast** [comment]
We should perhaps split this repo into the old and new one, as we went in a completely different direction by using @karst ’s music.

But like @IntelOrca said, none of the resulting files use these soundfonts anyway, so any releases/assetpacks are not  affected.

**Comment by ccoors** [comment]
You are right. This repo went in a completely different direction since I left. Sorry about that, it's just the way stuff goes sometimes. You should probably clear the entire history/create a blank repo and just transfer the files you need.

I was mostly interested in the fairground organ music, but since that didn't work out the way I thought that was a dead end. Really sorry about that :/

**Comment by Gymnasiast** [comment]
@ccoors Hey, don’t worry, this is still a *volunteer* project. And unlike a few years ago, it now seems likely we can make actual recordings of the Bressingham Voigt of our own, which will sound much more authentic anyway.

**Comment by ccoors** [comment]
@Gymnasiast That sounds amazing. I really hope it works out and would love to see that happen!

**Comment by gibmat** [comment]
> We should perhaps split this repo into the old and new one, as we went in a completely different direction by using @karst ’s music.
> 
> But like @IntelOrca said, none of the resulting files use these soundfonts anyway, so any releases/assetpacks are not affected.

Cool, thanks for the clarification. I do think it would be a good idea to scrub the repo or create a fresh one, just so going forward it's clear that everything in the repo is actually being used in the creation of the music tracks.

**Comment by gibmat** [comment]
Closing as my initial concerns aren't relevant to how releases are being done from this repo.

**Comment by Thaodan** [comment]
Just wondering why is opensfx license under CC-BY-SA-4.0 while the others e.g. title sequences and openmsfx are licensed under CC-BY-4.0?

**Comment by karst** [comment]
It's actually the other way around. For music we think it's important that artists are credited where credit is due, while for SFX we don't think it's necessary.
